@echo off
pushd %~dp0
git add .
set /p message="Message du commit: "
git commit -m "%message%"
git pull
git push
pause
echo `````````,zxxnnznxMMxxxxxMMMMMMMMMMMMMMxMxMMMMMxMxxxxxxxxnnnnnnnnnzznnznnnnnznzzznzzzzzznnzzzznzznz##zznnnznzzzznnnnnnnznzzz###zz###z#+;:.......``````
echo ````````.#xnnnnnxMMxnxxMMWMMMMMMMMMMMMMxxMMMMxMMMMxxxxxxxnnnnnnnnnnnzznnnnzznnzzzznnzzzzzzzzzzzzzzzzzzzzxxnznnznnnnnnnnnznzzz###zz##++#i,....`````````
echo ````````iMnnnxxMMMxxxMMWWWWMMMMMMMMMxMMMxxMxxMxxxMMxxxxnnnnnnnnnzzzzzzzzzzzzznzzzzzzznnzzznzzzzzzzznzzzzznnzznzznzznnzzznznzzz###z#z#++i,....`````````
echo ```````.nxxxxMMMMMnxMMWWWWWMMMMMMMMxxMMMMMxMxxxxxxxxxxnnnnnnnnnnzzzzzzz###zzzzzzzzzzzzznzzznznz#zz#znz#zzznzz#nzznzznzzznnznzzzzz###z##*:.`.``````````
echo ```````;xxxxMMMWxxxxxMMMWMMMMMMMMMMxMxMMMMxxxxxxxnnnnnnnznnnnnnnzzzzzzzz####zzzzzzzzz##zzzz#znn###zzznzzzzznzz#nzznnznnzzznznzzzzz###z#+;...``````````
echo ``````.zMxxMMWWxxxMMMMMMMMMMMMMMMMMMMMxMxxxxxxxxnnnnnnnznnznzzzzzzzzzz######zz#zzzzzz#####z###nnzz#zzznz#zznnzzznzzzzznzzznzznzzzzz###z+;,..``````````
echo ``````:nMMMWWWMxMMxMMMMMMMxMMMMMMMxMMMxxxxxxxxxnnnnnnnzzzzzz####zzzzz##############zzzzzz##zzz#zz####zznz#zzzzzzzznzzzzzzzznzzzz#zzzz##+i,.```````````
echo ``````+xMMWWWWxxMMMMMMMxxxMMMMMMMxxxxxxxxxxxxxxnnnnnnzzzzz##################+####z#zzzzzzzzzzzzzzzz#####nz#zz#zz##znzzzzzzzzzzzzz#zz#z##*,````````````
echo `````,xMWWMMMxxWMMMMMMMnxxxMxMMxxxxxxxxxMxxxxxnnnnnnzzzzz##+#++###+++++++++##+########zzzzzzzzzzzzz##zz#zzz#zzzzz#zznzznzzzznzzzzzzz##++*:````````````
echo `````*MMWWMMMxWMMMMMMMMMMxMMMxMMxMxxMxxxxxxnxnnnnnzzzzzzz#####+++++++++++++++++#########zzzz##nnzzzz##zz##zz#zzzzz#zznnznzzzzzzzzzzzzz#+*:.```````````
echo ````:xxWWxMMMMWWWMMMMMMMxxxMMxMMMxxxxxxxxxxnnznnzz#####z######++++++++++++++++++########zzzzzzzznnzzzz#zz##zzzzznnz#zznnnnzzzzznnzzzzzz#*:.```````````
echo ````#MMMMMWWWWWWWWWMMWWMMxMxMMxxMMxxxxxxxnnnznzzzz#####+####++++****+++*++++++++##########z#znzz#znz#nz##z##zzzznnzzzzznnnnnzzzznnnzzzz#*:.```````````
echo ```.xMMMWM0WWWWWWWWWWMMMMxxxxMxxxxxxxxxxnnnzzzz######++##+++++++++++++++++++++++++++#####zzzzzznzzzzzznnz#z##nzzznnnnnzzznnnnnnnnnnnzz#+*;.```````````
echo ```:WMW0WMMMMWWWWWWWMWMMMMMMxxMMxMMxxxxnnzzzzzzz###+##++++**++**+++++***++++++++++#+####zzznnzzznnzzznzznz####nzzznnnnnznnnnnnxxnnznnz##+i.```````````
echo ```;WWWWWWWWWWWWWWWMMMMMMMMMMMxxxxxxnnnnzzzzzz####++++++*++******************++*+++++++##z#zz##zzzzzznnzznzz###nznnnnnxnnnnnnnxxxnnnzzz#+;.```````````
echo ``.zWWMWWWMMMMMMMMxxxMMMMMxMMxxxxxxnnnnzzzzz###++++++*+++********iii*iii*******++++++#++##++#zzzzzzzzzznzzzzzzz#zzznnnnxnnnnnnnnxxxxnnzz#*,.``````````
echo ``,+WWMWMMMMMMMMMMMMMMxMMxxxMxxxxnnnnzzzz####+++++++*+*********ii*iiiii********+++*++++++++#zznzznnnznznnnzzzzznzzzznnxxnnnnnnnnnnxxnnz##i,.``````````
echo `.:zMWMMWW0WWWWWMMWMMMMWMMMMxxxxxnnnnzzz######++*+**************ii*iiii**************+++++####zzznnnnnzznnnz#zzznzznnnnxnnxxnnnnxxnnnnnz#i,..`````````
echo `:#MMMWWWWWWWWWMMMMMMMMMMxxxxxxnnnnzzzz######++*+**ii*iiiiiiiii****iiiiiiiii****+******++++###zzzznnnnzznznnzzzzznzzznnznnnxnxxnxxxnnnnz#*,..`````````
echo `ixMMMWWWWWWMMMMMMMMMxxxxxxxxxnnnzznnzz###+++*****iiiiiiii;iiiiiiiiiiiiiiiiii**********+++++####znnnnnnzznnnnnzznznz#znzznnnnnnnxxnnnzz#+*,..`````````
echo `+MMWWWMWMMMMWWMWMMMMMMxxxxxxnnnnnnzz####++***i*iiiiiiiiiiiiii;;iiiiiiiiiiiii***********++++##zzzzzznznnzznnnznzzzzzzzzzzzzzzznnnxxxnzz+**:..`````````
echo .nxMMxMMMMMWWWWWWMMMxxnxxnnnnnznzzz#z##+++**iiiiiiiii;;;;;;;;i;;;iiiiiiiiiiiiii****+****+++++##zzzzzznzznnnnnznnzzznnnzzzzzzzzznnnxnnnz#+i:..`````````
echo :xxxMMMWWWWWWWWMMMxxnnnnnnnnnzzzzz####++****iii;;;;;;;;;;;;;;;;ii;;;ii;iiiiiii*i********+++++##z##zzzzzznnnnnnnnnzzznnzzzzzz##zznnnnzzz+*i:..`````````
echo #xxMWW0WWWWWWWMxxxnnznnnnnnzzzzz#####+++**iiiii;;;;;;;;;;;;;;;;;i;;ii;;iiiiiiiiiiii********+++######z#zzzzznnznzzzzzzzzzzzzz#z##zznnznz+*i;,..````````
echo xMWWWWWWWWWWWMMxxxnznnnnzzzzzzzz###+++***iiii;;;;;;;;;;;;;;;;;;;;;;;;;iiiiiiiiiiii*i********++++######z##zzzzzzzzzzzzz#########zzzznnnn#*i;,...```````
echo MWWWMMMMMMMMMMxxnnnnnzzzz#zzz#####++++***ii;;;;;;;;;;;;;;;;;;;;;;;;;;;iii;;iiiiiii***i*******+++++##########zzzzz#######+#+++++#zzzznnn#*i;,..````````
echo WMMMWWWWWWMMMxxxxnnzzzzzzzz#+++##++*+**ii;;;;;;;;;;;;;;;;;::;;;;;;;;;iiiiiiiiiii*i**ii*********+++++##################+##++++*++#znnznz#*ii:..````````
echo MMWWWWWWWWWWxxxxnnzzzz#z##++++++++*****i;;;;;;;;;;;;;;:;::::;;;;;;;;;;i;;iiiiiiiiii**i*ii*******++++++########+++###++++++++***+##znznz#*i;,..````````
echo MW00WWWWMMMMxxxnnnzzz#z#++++++**+*****ii;;;;;;;;;;;;::::::::;;;;;;;;;;;;;;;iiiiiiii**iii**i*****++++++++++++++++++#+++++++++*+*+##zzzzz#*ii,..````````
echo WWWWWWWMMMMxMxnnnnzz###++**********i*iii;;;;;;;;:::::::::::::::;::::;;;;;;ii;iiiiiii**ii**i*i**********+++++++++++++++++++***++*+#zzzzz#*ii:..````````
echo MMMWW0Wxxxxxxxnnnnzz#++***ii*******i*iii;;;;;;;;;;:::::::::::::::::::::;;;;;;iiiiii*iiiii*ii**i**i********+****++++++++*++****+++###zzz#*ii:...```````
echo MMMWWMxxxxMxxxnnnzz#++**iiii*******i*iii;;;;;;;::::::::::::::::::::::::;;;;;;iiiiii*iiiii**ii*ii******i***********+**+++******+++#z#zz#+*ii;...```````
echo W00WMMxxxMxxxxnnnz##+**iiii*i*******i*ii;;;;;;;;:::::::::;;:;;::::::::;;;;;;;;iiiii*iiiiiiiiiiiii*iii*ii**********************+++#zz#zz#*ii;,.````````
echo 0WMMxxMMMxxMxxxnn##++*iii*ii**++******iii;;;;;:;;;::::;;;;;;;;;:::::::::;;;;;iiiiiii*iiiiiiiiiiiiiiiiiiiiiiii******************++##z##z+**i;,...``````
echo MMxxxxxMMxMxxxxn###+****ii***++++*****iii;;;;;;;;:::::;;;;;;;;;;;:::::::;;;i;iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii*****************+++#z##+#+***i,...``````
echo xxMWMMWMMMMMxxxz##+****ii****+++++****iiii;;;;;;::::;;;;;;;;;;;;;;;:::::;;;iiiiiiii*iiiiiiiiiiiiiiiiiiiiiiiii***********ii****+++#zz#+#+***i,....`````
echo W0WWWWWWWMWMxxzzz#++*iii**+++##++***i*iii;;;;;;:::::;:;;;;;;ii;;ii;;;;;;;;;iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii*************ii***+++#zz##++**+*,.....````
echo WWWWWWWWMMMMxnnzz#******++#++##++****iiiii;;;;;::::::::;;iiiiiiiiiii;;;;;;iiiiiiiiiiiiiiiiiiiiiiiiiii***iiii******************+++#zz##+***++,.....````
echo MWWWWWWWWWMxnnzz#+**+**+####++#+*****iiiii;;;;;;:::::::;;;;;iiiiii*iiii;iiiiiiiii*iiiiiiiiiii;iiiii*i***iiii***********ii****++++##zz#+***++:.....````
echo WWWMMWWWWMxxnnnz#+++++#zz##+++++*****iiiii;;;;::::::::::;;;;;i;;ii*iiiiiii;iii;iiiiiiiiiiiiiiiiiiii*i***iii*************ii***+++##z###+***++;....`````
echo MMMWWWWWxxxxxnnzz######z##+++*****i**iiii;;;;;;:::::::::;;;;;;;;;;;iiiiiiiiiiiiiii*iiiiiii*iiiiiiii*i***iii***i*********iii**++##zzz##+**++*:....`````
echo MWWWWWMMMMMxxnnnz##z###+++++******iiiiiii;;;;;::;;;;::::;;;;;;;;;;;;;;;;i;iiiiiiii*iiiiiii*iiiiiiiii***iii*ii*i****++****ii**++##zzzz##*i*++;.....``..
echo WWWWMMWWMMMxxxnzzzz######++++****iiiiiiiiiii;;;;:;;;;;;;;;;;;;;;;;;::;;;i;iiiiiii***iiiiii*iii*iiii****ii*iiii****+***********+#zznz##+*ii#+*......```
echo MMMWW0WWWMMxxnnzzzz#####+++++****iiiiiiiiiiiiiii;;;;;;;;iiiiiiii;::;;;;;;i;iiiiii**iiiiiii*iiiiiii*+**iii**i*****++**********++##nnnz#+*iiz+i.......``
echo MWWWWWWWWMMxxnnzn#######++++*****iiiiiiiiii;;;;i;;iiiii**iiii*i;;;;;;;;;ii;iii**i**iiiiiii**iiiiii++**+++*********+++*********++znnnzz+*i;#+;.........
echo WWWWWWMMMMMxxnnnz#z#zz##++++***i*iiii*iiii;;;;;;i**++++++++++****iiiiii*****ii*****iiiiii*+*iiiii*+++###++##+#++***+++********++znnnz#+iiii*i.........
echo MMMWMMMWMMMMxxnnzz#zz###+++****i*iiiiiiiiiii;;i****+##zzz#+++###+****+**+*++**i**+*iii*i**+*iii*+##zz####+++##+++++++++*+***+*++znnnz#+iiii*i.........
echo nxxMMMWMMMMMxnnnzzzzz###++++******iiiii*iiii;;iiii*++##znz#####zzz##+##+++++*****+*****i*++****+###z##++##zzzzzzz#######+***+*++znnnzz*ii**i*,........
echo +#nxxxMMWWMxxxnzzzzzz++++++++*****iii*i**iiiiiiii***++###zzzzz###zznznz####++++++*iii***++#++++##zzzzzznnzznzz#z#+#+#+++*++*++++znxnzz+i;*i**;........
echo ++znnxxMMMxxxnnnzzzz#++++++********ii**iiiiiiiiiii**++###zznnxnnnnnxnnnnzz######+*iii***+######zzznzznnzznnnz##+####++**+++++++#znxnzz+iii***;........
echo #znnnznnnxxxnnzzzzz#+#+++++*******i*ii*iii;;;;;iii**+***+#zzznxxxnnxxxxxxnnnnzzz+*******+#zzzznnnnnxxMMxxMMxxnnnz##+++**+++++++#znxnz#+i;i*i**,.......
echo zMWMxnnnnnnnzzzzzz####+++++*****+*****iiii;;ii***i******+++##znnnnxnnnxxxxxxxnn##*******++nxnxxxxMxxxxxMMMMxxnz###++*********++#znxnz#+iii*i*i,.......
echo xxMxxxnnnzzzzzz#######++++******++***++*iiiiiii********+++####znnnnznnnxxxxxxnzz#**iii**+#znnxxxxxxxxxxxxxxxnnzzz#++*******+++##zxxnz#*ii****i,.......
echo xnnnnnnnzzzzzzz######+++++*******+#+**************+####znnnxxxxMMMnzzzznxxxnnzzz#*iii****+znnnnnzznnnnnnzzzzzz####++*iiii+++++##zxnnz+*ii**++i:.......
echo nnnnnnzzzzzzzzzz####+++*+*********+#+***+*****++znxM00000WWWWMxnnxMxzzzznnnzzz##+*iiiiii*#znnnnz#znxMMxxnnz######+*+**i*i****+###nxnz+*iii+++i,.......
echo nnnz####zzzzzzzz###+++*+***++++****+#+**+++*++#nM00W0W000WMWWnxMxznxxnnzzzzzzzz#+*iiiii**#nnnnnnznxxxxxxxMxxnz##+++*******++*+###nnxz+iiii++**:.......
echo zzzz#+##zzzzz#zz###++**+***+*++******++++++##nMWMMMMWW0WWMWWMzzxMMnzznnzzzzz####+*iiiiii*#znnznnnnnxxW00xW0WWMxnz#+++***+++#++###nnnn+i**i+*+*:.......
echo zzz#++#z##zzz#zz###++*++*++++++++*****++++#zxMxz######zznnnz#####znnz+#zz#zz####+*iii;ii*#znnzzzznMMx0000#0W00WMMxnz#++*+++##+###nnnn+i***+++*,,,.....
echo zzz#######zz#zzz#z#+++++*++++++++++++**+##zxx#+**iiiiiii*iiii***++++##+++#######+*i;;;ii*+#znz##nMxnnMWWW0W000WMWWWMn##++++#+####nnnn+**+*#++i,,,,..,,
echo zzz####+##zzzzzz##++#++****++*+*+***++#++#zzz*iiiiiiiii;;i;iiii***+*+++*++#+###++*i;;;ii*++zzz#nnz######zznxxxxnnMMWWnz#+++#+####nnnn+*++*###*,,,,,,,,
echo #zz#+++#+++zzzzz##+#++**************iii*##zz*ii;iiiiiiiii;;;;iiii***++***+#++#+++*i;;;;i**+#zzz###+++++***+++++++#znMMn##+++#+###zzzz+*++*##z*,,,,,,,,
echo #zz#++++#++znzzz#+##++**++************+++**i*i;;;iii;;;;;;;;;iiii**++++++##++#++**i;;;ii**+####+++++++++*****i***++#nMxz#+++++###zzzz+*+#*##z*:,,,,,,,
echo ##z#+++++##nnnz#++##+++*++****+*******iiiiiiiiiiiiiiiiiiiiiiii****++++++++++++++*ii;;;;ii*+#####+++****iiii********+#Mxnz#++++###zzzz+*+#+#zz*,,,,,,,,
echo ###+++###zxMxnz#+++++*+*+++++****iiiiiii;;i*iiiiiiiiiiiiiiii*****++++++++++++++***i;;;iii*+##+#+++****iiiiii**ii****#zz#++++++###zzz##*##+###i,,,,,,,,
echo #+++++##znxMxnz#++++*+**+++***+***iiiiiiiiiiiiiiiii*************++++++++*++++++**ii;;;;iii+##++#+*++**********i****++++#++++++###z####*zz#z++i,,,,,,,,
echo +++++++##nxMnnz#++#**+*+++++++***iiiiiiiiiiiiiiiiiiii*****************+***++++*+*ii;;;;ii*+++++++**++****+********+**+***++#####+####+*zz#zz#i,,,,,,,,
echo +++++++##nxnnnz#+++++++++++++++**ii;;;iiiiiiiiiiiii***********iii****++****++++**ii;;;;ii*++++++++****+*+***+++++********+++####+###+++zzzz#+:,,,,,,,,
echo ++*++*++#nnzznz#+++++++++++++++*iiii;iii;iiiiii;iiii*iiiiiiiii;iiii**********+***ii;;;iii**++++++++*+*+******+++*+*++******++###+####++zz#+*;:,,,,,,,,
echo *+*+***+#zzz###+++#++++++++#+++**iii;;;;iiiiiii;i;;;;i;;;;;;;;;;;ii**********+***ii;;;;ii**++++++++**********i*************++++#+z#+#++z##+;:,,,,,,,,,
echo **++***+#zz##+++###+++++++++#++**iii;;;iiiiiiiii;;;;;;;;;;;;;;;;iii*********+++**ii;;;;i***+++**++*************iiiii******+*+++#+##+++*##+*;:,,,,,,,,,
echo **+++**+##+++**++####+++++#++++**iiii;iiiiiiiiiii;i;;;;;;;;;;;;;;ii*********+****ii;;;;ii**+**++++****iii**iiiiiiii**********++++#+*++*##+i:::,,,,,,,,
echo **+****+#+*****++#####+++###++++*iiiiii;;iii;;iiii;;;;;;;;;;;;;;;ii********++****iii;;ii**++**++++*****iii*iiiiiiii*****+****++++#++*+*+#+;,,,,,,,,,,,
echo **+****+++**i**++##z##++#####+++**iiii;;ii;;;iiiii;iii;;;;;;;;;;;i*********++****ii;;;;ii*+****++****iiiiiiiiiiiiiii*********++++#++*+*+#*:,,,,,,,,,,,
echo +*++*i**+**i*++++##zzz#######+++**i*iiiii;;;;iiiiii;i;;;;;;;;;;;iii********+*****ii;;;:;i******++****iiiii;;ii;iiiiii********+#++#++*+*++;:,,,,,,,,,,,
echo +*++*ii*+**i*+++*++zz#########++++***iii;;ii;iii;iiii;;;;;;;:;;;iiiii******++*****i;;;;;i****+++*****iiiii;;;;;iiiii****++***+#+#+++++*+*:,,,,,,,,,,,,
echo +*++**i*+***+###+++zzzz######++++++***iiiii;iii;;;;;;;;;;;;;;;;;iiiii****++++***iii;;;;iii***++++***iiiiii;ii;iiiiii*********+#+##++++++*::,,,,,,,,,,,
echo #*+#+***+***+###+++#z##########+++++***iiiiiiiiii;;;;;;;;;;;;i;iiiii***++++++***iii;;;;iii***+#++**iiiiiiiiiiiiiiiii*******+*+#+##++++++*:,,,,,,,,,,,,
echo #**#+**+#+**+#z#+++############+++++*****iiiiiii;;;;;;;;;;iiiiiiiii***+++#+#+***ii;;;;;iii***##++***ii*iiiiiiiiiii*********+*+#+##+#++++*:,:,,,,,,,,,,
echo z+*+++++++###zzz+++###z##########+++++****iiiiii;;;;;;;i;;iiiiiiiii****+####+**iii;;;iii*i***#z#+*****iiiiiiiiiiiii*******++*+#+##+##+++*:,,,,,,,,,,,,
echo vz+i*#++#++++#zzz#+++###############++++****iiiii;;;;;i;i;iiiiiiiii****+#####+**iiiii;ii**ii*+zz#+*****iiiiiiiiiiiii******+++++#####+++++*:,,,,,,,,,,,,
echo #+**+#++#++++#zx#++################++++****iiiiii;;;;;;iiiii;;iii****+#zzz##+*iiiii;ii***iii+zn#++****iiiiiiiiiiii*******+++++######++#+i:,,,,,,,,,,,:
echo +#+i+#++++++#znn#+++#################+++****iiiiiiiiii;iiiiiiiii***+++#nz###+*iiiiiiiiiiiii*+#nz+*******iiii*iii********++++++####z#+*++;,,,,,,,,,,,,:
echo +#+**+#+***+##zz#+++#################++++***iiiiiiiiiiiiiiiiiiii**+++#zz###+**iii;;iiiiiiiii*+nz+****i**iiiiiii*******+++++#+++##zzz#++*;,,,,,,,,,,:::
echo *#++i*+****+#+zz#+#######++###########++++***iiiiiiiiiiiiiiiiii***++#zn#++++*iii;;;;iiiiiiii*+#n++*******iiiii*******++++++#+++#znzz#++*:,,,,,,,,,,:::
echo i*++*i*****+++zz#########++##+#######+++++***iiiiiiiiiiiiiiiiii***+##zz+++***ii;;;:;;;iii;;i*++nz#+******iiii********+++++##++++##z#+***:,,,,,,,,:::::
echo i+##*i***++**++#z######++++#####+++#++++++********iiiiiiiiiii****++##z#**+++**iii;;;iiii;;ii**+#n#+**+*****ii******++++++##++++#z#+++**i:,,,,,,,,:::::
echo i+#z+i*++++**++#z########++#####+#++++++++*********iiiiiiiiii***++##zn#**++++*iiiiiiiiiiiii***++nz#++++************+++++####++*#z#++*+*;,,,,,,,,::::::
echo *+zn#*++++++**+########+++++#####+++++++++********iiiiii**iii**++##zzn#+++#z#+****ii**iii****+#+zn#+++++***********+++++##+#++*#nz++*+*;,,,,,,,,::::::
echo *+nxn++++++***+++######+++++#######+++++++++*****i**iiiii*****++##zzzn###znnzz++***++++++++++###znz#++++***********+++#+##+#++*+z#**+*i:,,,,,,,,::::::
echo +#nMxz###++******######++++#+++###+#++++++++*****i***iiiii****++#zz#znzzznxMWxz#+++###+++###zz##nxz#++++++*********+++#+#++#+**+##****i,,,,,,,,,::::::
echo +zxxxxnz#++******######+++++++###+++++++++*******************+++#z#+#nnnxxM00WMzz###z#####nMxxnzxnn##++#++********++++##+++++**+#+**ii:,,,,,,,,,::::::
echo +nxxxMxnz#+++++++#######+++++++###+++++++********************++###++#zxMMMWWWMMxnnzzzzzzzn0WMxxnnnzz####+++*******++++##+++++**++++*ii,,,,,,,,,,,,,:::
echo #nxxxMMMxz#######nz#####+++++++#+##+++++*+***+*******i******+++#+++*+#nMWWMMMxxMMxxnnnnzxW0WMMxnnzzz###+++++*****++++++##+++++*++++**;,,,,,,,,,,,,,,,:
echo zxxnxxMWMxnnzzznnxz#####++++#+###+##+++++*++++***************++++****+#znxnzzznxxxMxxxxMMMMMxxnzzzzz#####+++**+++++++++##+++++*+++***:,,,,,,,,,,,,,,,:
echo nxnnxMWWMWMxxxxMMMn#####++++#+#+#+++++****+++*+**************+++*****+++####++#znxxxMMxxnnxnnnzz###z##+++++***+**+++++++++++++*+++*+;,,,,,,,,,,,,,,,,,
echo nnnnxMMWWWWxznnxxxnz#####+++#+++++++++****+++**+***********++*+**iii***++++++++##znxxnnzzzzzzz###########++***+*++++++++#++++++++***,,,,,,,,,,,,,,,,,,
echo nnznxMMWWWWxzzzznnnz#####+++++++##++++********+*************++**iiii******+++++++#zzzzzz##z######++####+++++++*++++++++++++++++++++i,,,,,,,,,,,,,,,,,,
echo nzznnxMWWWWn##zzznnz#######++#####+++++******+****************iiiii********+++*+++###########++##+++###++++++*++++++++++++++++*+++*:,,,,,,,,,,,,,,,,,,
echo nzzznxMWWWWn###zzzzz###############+++++*****+**************iiiiiiiiii*****++***+++++++#+++++++++++++##+#++++++*+++++++++++**++##+:,,,,,,,,,,,,,,,,,,,
echo nzzznxxMMWMn####zzzzz#########+###++++++*+*****************iiiiiiiiiiii*************+++++++++++*++++++#++++++++*+++*++++++++*++#+:,,..,,,,,,,,,,,,,,,,
echo zznznnnxxMMz++#####zzzz###########++++++**+****************iiiiiiiiiiii*****i*******+++++++++++*+++++++#+++++++****+*++++++***+*:,....,,,,,,,,,,,,,,,,
echo zznnnnnnnnxz++#+###zz#zz###zz####+++++++******************iiiiiiiiiiiiii****i**i********+++++++*+++++++#+++++++*+***+++++++***;,.......,,,,,,,,,,,,,,,
echo zzznzzz##zn#++##+##zzzzzzz##z######++++++****+****+*******iiiiiii*iii***i*****ii**********+++++*+++++**+++++++++++**+++++++***:..........,,,,,,,,,,,,,
echo zznnz##**#z#++++++#zzzzzzzz####+###++++++*****************iiiiiiiiii**iii*****i***********++++++*+*+*+*+#+++++++***+*+++++++*+,.........,,,,,,,,,,,,,,
echo znnn#++*i*#+**+++++#zzzzzzzz###+###+++++++****i**********iiiiiiiiii**********iiiiii***i*i**+++++++++**+*+#++*******++++++++***,.........,,,,,,,,,,,,,,
echo nnnn#**iii+++**++#+#zzzzzzzzzz###+++++++++******i********iiiiiiii************iiiiii******i***++++++++++*++++*********++++++***,..........,,,,,,,,,,,,,
echo znnn+**iii*+**+++++#zzzzzzzzzz###++++++++++*****ii********iiiii****************iiiiii********++++++++++**+++********+++++++++i.........,,,,,,,,,,,,,,,
echo znnz+**i;;i*+**++++#zznnzzzzz#z###++++++++****i**i*********i******++**************iii**+++++*++++++++++++++++********++++++++;...........,,,,,,,,,,,,,
echo #nn#**i;;ii*+**++++#nznnzznzz######+++++++*****iiii*********+++++++****++++++++++++**++#++++++++++++++*+++++**********+++++++:...........,,,,,,,,,,,,,
echo +zn#iii;;;;*+***+++#zzznnnnzzz####+++++++++****iiiii****+++++++###+++++++#+######+#+###z######+++++++*++++++***********++++++,..........,,,,,,,,,,,,,,
echo echo +zn#*i;;::;;++**++++zznzznnzzz#####+++++++*****ii*iiii**+++++#zzzzzzzzzz#######zzz####zzz####zz###++++++++***********+++++++*,.........,,,,,,,,,,
echo +znz+*i;:::;*+**++++znnzznnnnzzz###++++++++*****iii****++++##znxxxxxxxxnnnzzznnxnnnzznxMxxxnzzznzz##+++++************+++++++i.............,,,,,,,,,,,,
echo +#zz#*i;;:;i#+**+#++zznnnnnnnzz#####+++++++*****iii****+++#nxxnnnnnnnzzzznnnxxxnnxxxxxnzznnxxxMMMxxz#++++****ii*****++++++++;...........,,,,,,,,,,,,,,
echo i+zzz#+*i;i#z+***+++#znnznnnnnzz#####+++++++*****iiiii**++#z#+***iiii*iiiiiii*******+++******+##zzznnz#++************++*++++,..........,,,,,,,,,,,,,,,
echo ;i+#++#+++zznz+*++++#nnnnnnnnnzzz###+++++++****iiiiiii*++++***ii**iii;;;;;;;;;iiii;iiiiiiiii;iii***+#z#++*iiiii*****+**+++#*.............,,,,,,,,,,,,,
echo ;;i*****+xMMMn++++++#znnnnnnnnnnz###+++++++*****iiiii*********ii**+***ii;;;;;;;;;;;ii;;;;;iii********+++**iiii******++++++#;.............,,,,,,,,,,,,,
echo :::;ii*+M000W*+++++++zznnnnnnnnzzz##+#++++*+*****i*i*******iiiii**+++++***iiiii;;;;;i;iiii**+++++*****++**iiii***+++*++++##,...........,,,,,,,,,,,,,,,
echo ,::;;;*M00#0n:;#+++++zznnnnnnnnzz####+#++#++++*****i***+****iiii**+##z####+++++********++++++##++******+**ii*******+++++##+............,,,,,,,,,,,,,,:
echo ,,:::in0##00+,,++++++znnnnnnnnnnzzz##+++##+++++**********i*********+#zzzzzzzzzz#########zz#z####+++++++*+*ii*******+++####i..............,,,,,,,,,,,,,
echo ,,,:;z00#00M;,.i++#++#znnnnnnnnnzzz###+##+++++++***+*******+***+++**+##znnxxxxnnxnnxxxnnnnnnz###++++++++************+++##+:............,,,,,,,,,,,,,,,
echo ,,,:#0##000z,,.,++#++#znnnnnnnnnzzzz######+++++***************++++++++####zzznnnnnnnnxxnnnzz#####++#+++++*****+**++++++##*,............,,,,,,,,,,,,,,:
echo ,,:*W###00W*,...i##++#zzznnnnnnnnzzzz######+++++++++********++++++++++++++###########zz#z###########+++++++**+****+++++##;...............,,,,,,,,,,,,,
echo ,,ix0###00M;....:#+#++#zznnnnnnnnzzzzz######++++*********+++++++#++++++++++++++++++++#################++++*++*+++*++####+,...............,,,,,,,,,,,,,
echo ,;x0####00x:.....*##++#zznnnnnnnnnzzz##zz###++++++******i***+++++++++++++*****+*****++++++++#########+++++*++*++++++####i...............,,.,,,,,,,,,,,
echo :#0#####00z,.....,++++#zzzznnnnnnnzzzzz#####+++++++*******ii***+++++++++*************++++++##++######++++++++*++++######,..............,,,,,,,,,,,,,,,
echo +W######00#,......i+#++#zzzzzznnnnnnzzz#######+++*++****iiiii****++*++****************+++++++++++#+++++++++++++++++####i..............,,,,,,,,,,,,,,,:
echo W0#####000+.......,+#++#zzzznznnnnnnzzzzzz#####+++****i*************+*****i**i****i******++++++++++++++++++++++++####z#,................,,,,,,,,,,,,,,
echo 0######000*........;#+++#zzzznnnnnnnnzzzzz######++*****************************i*iii****++**+*++++++++*++++++####+###z*...............,,,,,,,,,,,,,,,,
echo #0#####000*.....``..*#++#zzzzznnnnnnnnzz##z#####+++++***iii*ii**i**********i***iiiii*****+***+**++++***+++++#######zz#:..............,,,,,,,,,,,,,,,,,
echo #######000*....````.:#+++##znzznnnnnnzzzzzz####++#++++*****ii**************iiiii**ii****************+**+*+++++######z*,..............,,,,,,,,,,,,,,,,:
echo #######000*....`````.i#++##zzznnnnnnnnnzzz#########+++******iiii********++*i*iiii*iiiiii***************+*+++++####zz#:...............,,,,,,,,,,,,,,,,,
echo 0######000+....``````.*+++##znznnnnnnnnnnzzzz##zzz####++****iiii******+++***iii**i*********************++++++####zzz*.................,,,,,,,,,,,,,,,,
echo #######000#...````````:+++##zznnnnnnnnxnnzzz#zzzzzz####++****iii******+++*****i*i**********************++++#####zzz#:,..............,,,,,,,,,,,,,,,,,,
echo ######0000#...````````.;++###zznnnnnnxxxnnnzzzznnnnzzz###++**i*i*******++++************+**************++######zzzzz*,...............,,,,,,,,,,,,,,,,,,
echo ##### ###00z...`````````.i++##zzznnnnnnxxxxnnnnnnnnnnnzzz##++*************++*******i***+*****+*******+++#####z#zzzz#,,..............,,,,,,,,,,,,,,,,,,:
echo ########00n,.```````````.*+++#zzznnznnxxxxxxxxnnxxxxnnzzz##+++****+++++++++*++*****++***++++++****++++###zzzznnzzni,,........,......,,,,,,,,,,,,,,,,,,
echo ########00x,.````````````,+++#zzznnnnnnxxxxxxxnnxxxxxnnzzz###++++*+++++++****++++++++**++++++++**++++##zzzznnnnnn#,,,..............,,,,,,,,,,,,,,,,,,,
echo ########00M:.````````````.:++##zzzznnnnnxxxxxxxxxxxxxnnnzzzzz#++++++++++++++*+++++++*+++*++++++*+++##zznnnnxnnnn#:,,,,....,,......,,,,,,,,,,,,,,,,,,,,
echo ########00Wi.`````````````.;+##z#znnnnnnxxxxxxxxxxxxxxxnnzzzz##++++++++++++++++###++++*+++###+++####znnxxxxxxxnn;.,,,.,..,,,.....,,,,,,,,,,,,,,,,,,,,,
echo ########00W+.``````````````.i##zzzzznnznnxxxxxxxxxxxxnxnnnnnz###++++++++++#+++++##++++++########zzzznxxxxxxxnxni,.,,.,,..,,,,....,,,,,,,,,,,,,,,,,,,,,
echo ########000z..``````````````.i#zz#zzzzznnnxxxxxxxxxxxxxnnnnnnz##++++##########+###++####z###zzzzzzznxxxxxxxxxni..,,,.,,.,,,,,......,,,,,,,,,,,,,,,,,,,
echo ###00###000x,.```````````````.*#z##zzznnnnnxxxxxxxxxxxxxnnnnnzzz######z######+##########zzznzzzznnnnxxxxxxxxn;,.,,...,...,,......,,,,,,,,,,,,,,,,,,,,:
echo ########000W;.```````````````..i###zzznnnznxxxxxxxxxxxxxxxxnnnnnzzzzzzzz#zz#z######zzzznnxxnnznnxxnxxxxxxxxz:,.,,,...,,..,,,...,,,,,,,,,,,,,,,,,,,,,,,
echo #########000z,.`````````````````.;+#zzzzzzzznxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxnnnzznnnxxxxxxxxxxxxxxxxxxMxxxW0#:,,,,,,.....,,,..,.,,.,,,,,,,,,,,,,,,,,,,,
echo #########000n:.``````````````````.;###zznzzzznnnxxxxxxxxxxxxxxxxxxxxxxxxxxxxnxnnxxxxMMMMMMMMMMxxxxxxxMxxW#0W*,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,,,,,,,,,
echo #########00x;..``````````````````.:+##zzzzzzznnnxxxxxxxxxxxxxxxxxxxxxxxMMMxxxxxMMMMMMMMMMMMMMxxxxxxxxxW####xi,.,,.,..,.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
echo ##########00W*..```````````````````.:*#zzzzzzznnnnnnnnnxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMMMMMMMxxxxxxxxnz0####0x*:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
pause